### PR TITLE
Updated the SimCache toolbar icon

### PR DESCRIPTION
**Pull request by StevenFrost**

### CODE REVIEW

**Review by ollyau — APPROVED** [review]
Nice work!  I'm fine with this, but do we want to tag @HughesMDflyer4 too?

**Comment by HughesMDflyer4** [comment]
image

I think it might be nice to maintain the bounds that the default icons seem to stay within, not sure how that's handled though.

**Comment by StevenFrost** [comment]
Updated the icon. Here's a screenshot of the toolbar, EFB and pinned app:

image

**Review by ollyau — APPROVED** [review]
Looks reasonable at the sizes in the screenshot!

**Review by HughesMDflyer4 — APPROVED** [review]
Looks good!

**Pull request merged**
